- name: Local Dotfiles Config
  hosts: localhost
  connection: local
  pre_tasks:
    - name: Update packages
      become: true
      ansible.builtin.package:
        update_cache: true
        state: present
  roles:
    - bitwarden
    - ssh
    - git
