- name: "Install Productivity tools"
  community.general.pacman:
    name:
      - lazygit
      - fzf
      - ripgrep
      - fd
      - eza
      - bat
      - xclip
    state: present
  become: true
