- name: "Install nodejs"
  community.general.pacman:
    name:
      - nodejs-lts-iron
    state: present
  become: true

- name: "Install npm"
  community.general.pacman:
    name:
      - npm
    state: present
  become: true

- name: "Install n"
  community.general.npm:
    name: n
    global: true
  become: true
