- name: "Include distribution tasks"
  ansible.builtin.include_tasks: "include-distribution-tasks.yml"

- name: "Create config folder"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/nvim"
    state: directory
    mode: "0755"

- name: "Create symlink to role files directory"
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ ansible_user_dir }}/.config/nvim"
    state: link
    force: true
